## Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jfood_account?useSSL=false&characterEncoding=UTF-8
    username: root
    password: 1234

## Hibernate Properties
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true
# Hibernate ddl auto (create, create-drop, validate, update)
        ddl-auto: update

security:
  oauth2:
    resource:
      user-info-uri: http://localhost:2108/v1/account/info
      filter-order: 3